### PR TITLE
Fix install script on arch linux

### PR DESCRIPTION
**Pull request by koep**
Hey,

this fixed the DCOS CLI installation on arch linux for me (arch uses python 3.x as default).

I'm not sure if this lives up to your standards though - feel free to comment / close.

### CODE REVIEW

**Comment by jsancio** [comment]
@koep, DC/OS CLI should work with python3. What error were you getting?

**Comment by koep** [comment]
My description is a bit misleading. Arch uses Python 3.5.x ;-)

> Python 2.7.x or 3.4.x: Installed by default on OS X and most Linux distributions. (Python 3.5.x will not work.)

**Comment by jsancio** [comment]
I see. It probably works against Python 3.5.x. It is just that we only have integration tests against 2.7 and 3.4.

**Comment by koep** [comment]
I can provide the exact error message as soon as I get back to my arch linux computer.

**Comment by koep** [comment]
```bash
$ source /tmp/dcos/bin/env-setup && dcos help

Traceback (most recent call last):
  File "/tmp/dcos/lib/python3.5/site-packages/dcoscli/subcommand.py", line 96, in run_and_capture
    exit_code = m.main([self._command] + self._args)
  File "/tmp/dcos/lib/python3.5/site-packages/dcoscli/help/main.py", line 18, in main
    return _main(argv)
  File "/tmp/dcos/lib/python3.5/site-packages/dcoscli/util.py", line 21, in wrapper
    result = func(*args, **kwargs)
  File "/tmp/dcos/lib/python3.5/site-packages/dcoscli/help/main.py", line 31, in _main
    return cmds.execute(_cmds(), args)
  File "/tmp/dcos/lib/python3.5/site-packages/dcos/cmds.py", line 43, in execute
    return function(*params)
  File "/tmp/dcos/lib/python3.5/site-packages/dcoscli/help/main.py", line 79, in _help
    with ThreadPoolExecutor(max_workers=len(paths)) as executor:
  File "/usr/lib64/python3.5/concurrent/futures/thread.py", line 96, in __init__
    raise ValueError("max_workers must be greater than 0")
ValueError: max_workers must be greater than 0
```

**Comment by jsancio** [comment]
@tamarrow and @koep, I am looking into this now.

**Comment by jsancio** [comment]
@koep I am unable to reproduce this. It looks like an invalid installation. Can you provide the output for:

1. `/tmp/dcos/bin/dcos --version`
1. `ls -l /tmp/dcos/bin`

@tamarrow Do you know what could be happening?

I have a fix for the python exception (#619). It doesn't fix your problem (not having any subcommands) but it will safe guard against the python exception.

**Comment by tamarrow** [comment]
Not sure, seems to be some path problem. @koep can you also provide the output for `dcos help --log-level=debug`. Thanks!

**Comment by koep** [comment]
```bash
$ /tmp/dcos/bin/dcos --version
dcos version 0.4.4
```

```bash
$ ls -l /tmp/dcos/bin
total 128
-rw-r--r-- 1 cko cko  2068 May 20 09:02 activate
-rw-r--r-- 1 cko cko  1010 May 20 09:02 activate.csh
-rw-r--r-- 1 cko cko  2208 May 20 09:02 activate.fish
-rw-r--r-- 1 cko cko  1137 May 20 09:02 activate_this.py
-rwxr-xr-x 1 cko cko   218 May 20 09:02 dcos
-rwxr-xr-x 1 cko cko   237 May 20 09:02 easy_install
-rwxr-xr-x 1 cko cko   237 May 20 09:02 easy_install-3.5
-rwxr-xr-x 1 cko cko   573 May 20 09:02 env-setup
-rwxr-xr-x 1 cko cko   220 May 20 09:02 jsonschema
-rwxr-xr-x 1 cko cko   209 May 20 09:02 pip
-rwxr-xr-x 1 cko cko   209 May 20 09:02 pip3
-rwxr-xr-x 1 cko cko   209 May 20 09:02 pip3.5
-rwxr-xr-x 1 cko cko   225 May 20 09:02 pkginfo
-rwxr-xr-x 1 cko cko   222 May 20 09:02 pygmentize
-rwxr-xr-x 1 cko cko   219 May 20 09:02 pyrsa-decrypt
-rwxr-xr-x 1 cko cko   235 May 20 09:02 pyrsa-decrypt-bigfile
-rwxr-xr-x 1 cko cko   219 May 20 09:02 pyrsa-encrypt
-rwxr-xr-x 1 cko cko   235 May 20 09:02 pyrsa-encrypt-bigfile
-rwxr-xr-x 1 cko cko   217 May 20 09:02 pyrsa-keygen
-rwxr-xr-x 1 cko cko   240 May 20 09:02 pyrsa-priv2pub
-rwxr-xr-x 1 cko cko   213 May 20 09:02 pyrsa-sign
-rwxr-xr-x 1 cko cko   217 May 20 09:02 pyrsa-verify
-rwxr-xr-x 1 cko cko   230 May 20 09:02 pystache
-rwxr-xr-x 1 cko cko   228 May 20 09:02 pystache-test
-rwxr-xr-x 1 cko cko 10432 May 20 09:02 python
lrwxrwxrwx 1 cko cko     6 May 20 09:02 python3 -> python
lrwxrwxrwx 1 cko cko     6 May 20 09:02 python3.5 -> python
-rwxr-xr-x 1 cko cko  2327 May 20 09:02 python-config
-rwxr-xr-x 1 cko cko   217 May 20 09:02 rollbar
-rwxr-xr-x 1 cko cko   216 May 20 09:02 virtualenv
-rwxr-xr-x 1 cko cko   216 May 20 09:02 virtualenv-3.4
-rwxr-xr-x 1 cko cko   216 May 20 09:02 wheel
```

```bash
$ ./dcos help --log-level=debug
Command not recognized

Usage:
    dcos help
    dcos help --info
    dcos help <subcommand>
```

**Comment by jsancio** [comment]
@koep, We gave you the wrong command. The command is `dcos --log-level=debug help`.

**Comment by jsancio** [comment]
Never mind @koep. I was able to reproduce your issue. #619 should fix it. @tamarrow do we have an ETA on the next release of the DC/OS CLI?

**Comment by koep** [comment]
Very nice, thanks @jsancio @tamarrow .

**Comment by tamarrow** [comment]
@koep will do a release early next week. Thanks!

**Pull request closed without merging**
