### PR TITLE
Displayed variant when running dcos --version.

### PR DESCRIPTION
**Pull request by ArmandGrillet**

### CODE REVIEW

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run all integration tests

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run integration tests

**Comment by ArmandGrillet** [comment]
Which changelog?

**Comment by bamarni** [comment]
Seems like we don't have it yet on master (https://raw.githubusercontent.com/dcos/dcos-cli/0.7.x/CHANGELOG.md). It should look like this for now : 
```
# CHANGELOG

## Next

* Features

  * Displayed variant when running dcos --version
```

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run integration tests

**Pull request merged**
