### PR TITLE
Updated HTTP headers for `dcos task exec` based on Mesos changes.

### PR DESCRIPTION
**Pull request by klueska**
This PR is dependent on https://github.com/dcos/dcos/pull/1179
It should not be merged until this PR has landed.

### CODE REVIEW

**Comment by tamarrow** [comment]
@klueska once this is merged, how will old builds respond?

**Comment by klueska** [comment]
They will break with an error of:
```

Error while fetching [
https://35.184.88.0/slave/3f67c585-735c-4c1f-8115-57aeecbea113-S0/api/v1]:
HTTP 406: Not Acceptable
```

**Comment by tamarrow** [comment]
@klueska can we not support both? Or is this solely in 1.9 so no customers will be adversely affected?

**Comment by klueska** [comment]
This is only in 1.9, so no one will be affected.

**Comment by tamarrow** [comment]
👍

**Pull request merged**
