### PR TITLE
Refactor Jenkinsfiles

### PR DESCRIPTION
**Pull request by bamarni**
This extracts common code between Jenkinsfiles into a dedicated base file.

### CODE REVIEW

**Comment by bamarni** [comment]
run linux integration tests

**Comment by bamarni** [comment]
run linux integration tests

**Comment by klueska** [comment]
I don't think this will work unless you do something like:
https://stackoverflow.com/questions/37800195/how-do-you-load-a-groovy-file-and-execute-it

Also, "Factorize" is not a word in english, so you mean "Refactor"?

**Comment by bamarni** [comment]
> Also, "Factorize" is not a word in english, do you mean "Refactor"?

Yes :smile_cat: 

I've tried the other approach with the last commit, however I think it doesn't work outside from a node block.

**Comment by bamarni** [comment]
run linux integration tests

**Comment by bamarni** [comment]
run linux integration tests

**Comment by bamarni** [comment]
run linux integration tests

**Comment by bamarni** [comment]
At this point I'd rather do this during the 1.12 refactoring.

**Pull request closed without merging**
