### PR TITLE
Stop supporting the legacy config location

### PR DESCRIPTION
**Pull request by bamarni**
This has been deprecated since 0.5 and there were a migration path in
place. As we don't provide it anymore we're dropping support for it
altogether.

https://jira.mesosphere.com/browse/DCOS_OSS-3966

### CODE REVIEW

**Comment by bamarni** [comment]
@mesosphere-ci run integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run integration tests

**Comment by takirala** [comment]
@mesosphere-ci run integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run integration tests

**Pull request merged**
