### PR TITLE
Update package integration tests for DC/OS 1.12

### PR DESCRIPTION
**Pull request by bamarni**
This uses the helloworld universe image generated by the following PR : mesosphere/universe#1751

It also removes the frozen version of the main Universe. The reason for this was probably to satisfy all fixtures from package integration tests. But this introduces technical debt as each time we need to upgrade it there is a bunch of tests failing and we have to update all sort of messages assertions which comes from Cassandra, Chronos and other packages. This updates some of the tests to use helloworld instead.

### CODE REVIEW

**Comment by bamarni** [comment]
run linux integration tests

**Comment by bamarni** [comment]
run linux integration tests

**Comment by bamarni** [comment]
run linux integration tests

**Comment by bamarni** [comment]
run linux integration tests

**Comment by jsancio** [comment]
LGTM. Thanks @bamarni

**Pull request merged**
