### PR TITLE
[0.7] Check for plugin viability when adding it to the CLI.

### PR DESCRIPTION
**Pull request by ArmandGrillet**

### CODE REVIEW

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run integration tests

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run integration tests

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run integration tests

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run integration tests

**Pull request merged**
