### PR TITLE
Fix packaging tests to work with the latest version of DC/OS

### PR DESCRIPTION
**Pull request by larioj**
This fixes tests that check labels that no longer exists. It also changes the universe servers used by the tests since the old version cannot handle the new requests.

### CODE REVIEW

**Comment by karlkfi** [comment]
Ignore the `test-install-script-multijob` test. It was added for another PR that isn't merged yet.

**Comment by tamarrow** [comment]
@larioj your experimental tests failed: https://teamcity.mesosphere.io/viewLog.html?buildId=655874&buildTypeId=DcosIo_DcosCli_OsX_MacBinary&guest=1

@karlkfi please do not add your job to github reporting yet. Also if would be better to add it to the existing CIs so we don't have more CIs to manage.

**Comment by larioj** [comment]
@tamarrow Yeah, I saw that. The latest changes should fix that.

**Comment by karlkfi** [comment]
@tamar: I'll disable the MultiJob build trigger.  

I added it to Jenkins because the non-windows tests for the cli still haven't been migrated from TeamCity yet. 

My new MultiJob build can easily have new tests added to it as separate parallel or serial jobs if you want to test on the same cluster. It should make migrating to Jenkins trivial. 

If you know how to execute win-bash in Jenkins I can add the Windows test.

**Comment by tamarrow** [comment]
@mesosphere-ci rebuild

**Pull request merged**
