### PR TITLE
Fix subprocess.PIPE import error

### PR DESCRIPTION
**Pull request by TerryHowe**

### CODE REVIEW

**Comment by tamarrow** [comment]
@TerryHowe thanks for the pr! Can you explain how this fixes the error you were seeing?

**Comment by TerryHowe** [comment]
I think the real problem is subprocess is majorly overloaded here and this is trying to import the system subprocess.py, but there is also a local subprocess.py file.  This fixes https://github.com/dcos/dcos-cli/issues/774

Anyway without this fix:
```
ansible $ dcos help
Traceback (most recent call last):
  File "/Users/THowe/.venv/bin/dcos", line 7, in <module>
    from dcoscli.main import main
  File "/Users/THowe/.venv/lib/python2.7/site-packages/dcoscli/main.py", line 7, in <module>
    from dcos import config, constants, emitting, errors, http, subcommand, util
  File "/Users/THowe/.venv/lib/python2.7/site-packages/dcos/config.py", line 10, in <module>
    from dcos import constants, jsonitem, subcommand, util
  File "/Users/THowe/.venv/lib/python2.7/site-packages/dcos/subcommand.py", line 12, in <module>
    from subprocess import PIPE
ImportError: cannot import name PIPE
```

**Comment by TerryHowe** [comment]
To show it is an overloading issue with the local subprocess.py:
```
ansible $ echo 'PIPE=-1' >>/Users/THowe/.venv/lib/python2.7/site-packages/dcos/subprocess.py
ansible $ dcos help
Command line utility for the Mesosphere Datacenter Operating
System (DC/OS). The Mesosphere DC/OS is a distributed operating
system built around Apache Mesos. This utility provides tools
for easy management of a DC/OS installation.

Available DC/OS commands:

	auth           	Authenticate to DC/OS cluster
	config         	Manage the DC/OS configuration file
	help           	Display help information about DC/OS
	job            	Deploy and manage jobs in DC/OS
	marathon       	Deploy and manage applications to DC/OS
	node           	Administer and manage DC/OS cluster nodes
	package        	Install and manage DC/OS software packages
	service        	Manage DC/OS services
	task           	Manage DC/OS tasks

Get detailed command description with 'dcos <command> --help'.
ansible $
```

**Comment by tamarrow** [comment]
Thanks for providing those screenshots! Lets rename the two subprocess imports with `as x` to prevent this from happening again. 

ok to test

**Comment by tamarrow** [comment]
@TerryHowe ^ The import is no longer in pep8 compliant order. If you run `tox -e py34-syntax` you will see the error, or look at the CI output: https://teamcity.mesosphere.io/viewLog.html?buildId=433547&buildTypeId=DcosIo_DcosCli_Ci&tab=buildLog#_focus=1231

**Comment by tamarrow** [comment]
Thanks @TerryHowe! Can you please rebase your branch?

**Comment by tamarrow** [comment]
thanks @TerryHowe!

**Pull request merged**
