### PR TITLE
Sort package versions by release version

### PR DESCRIPTION
**Pull request by jsancio**

### CODE REVIEW

**Comment by jsancio** [comment]
Can we review this? I would like to ship this in the next CLI release.

**Comment by tamarrow** [comment]
@jsancio can we add a quick unit test for this or change the `test_describe_package_versions` integration test to one that has more than 1 version?

**Comment by tamarrow** [comment]
@jsancio please rebase

**Comment by jsancio** [comment]
@tamarrow Done. Merged master.

**Comment by tamarrow** [comment]
@jsancio `test_describe_package_versions` failed: https://teamcity.mesosphere.io/viewLog.html?buildId=526041&buildTypeId=DcosIo_DcosCli_Ci&guest=1

**Pull request merged**
