### PR TITLE
Fixes after bad merge

### PR DESCRIPTION
**Pull request by janisz**
By a mistake previous commit (f4361b13c82d257cc99c7ae6df9957ded950e6aa) introduced not formatted code. This commit is a follow up to format the code.

### CODE REVIEW

**Comment by janisz** [comment]
@mesosphere-ci run linux integration tests

**Comment by janisz** [comment]
@mesosphere-ci run integration tests

**Comment by janisz** [comment]
@mesosphere-ci run integration tests

**Comment by janisz** [comment]
@mesosphere-ci run integration tests

**Comment by janisz** [comment]
@mesosphere-ci run integration tests

**Comment by janisz** [comment]
@mesosphere-ci run integration tests

**Comment by janisz** [comment]
:wave: @drewvanstone @br-lewis @makkes @rgo3  Can you review, please?

**Comment by makkes** [comment]
@mesosphere-ci run integration tests

**Pull request merged**
