### PR TITLE
Try to make install work on old cluster

### PR DESCRIPTION
**Pull request by jsancio**

### CODE REVIEW

**Comment by jsancio** [comment]
@klueska check it out.

**Comment by jsancio** [comment]
@klueska The Linux test pass. Should we run this again?

**Comment by jsancio** [comment]
@klueska Re-running the tests.

**Comment by bamarni** [comment]
@jsancio : had you also tried to run tests locally? I personally see an error on the test from this PR, I think those tests are not covered by CI at the moment. (cf. #1038)

**Pull request merged**
