### PR TITLE
update ccm template to use env var for cloudformation template

### PR DESCRIPTION
**Pull request by tamarrow**

### CODE REVIEW

**Comment by jsancio** [comment]
And we are going to update the TC build to specify the template?

**Comment by jsancio** [comment]
LGTM! :shipit:

**Comment by tamarrow** [comment]
Yep, updated the CIs

**Comment by jsancio** [comment]
Lgtm!
On Wed, Jul 6, 2016 at 16:21 tamarrow <notifications@github.com> wrote:

> Yep, updated the CIs
>
> —
> You are receiving this because you were assigned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/dcos/dcos-cli/pull/676#issuecomment-230936454>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAwfGgXUECuP_Jaqc8Tnzk7vTKKdjF8Tks5qTDhfgaJpZM4JGjwe>
> .
>
-- 
José Armando García Sancio
Mesosphere

**Pull request merged**
