### PR TITLE
Updated description of ssl_verify.

### PR DESCRIPTION
**Pull request by ArmandGrillet**
Give more context regarding the certificates used if the value of `ssl_verify` is set to `True`.

### CODE REVIEW

**Comment by bamarni** [comment]
Adding @jgehrcke for review as the original reporter (https://jira.mesosphere.com/browse/DCOS-13067).

**Comment by ArmandGrillet** [comment]
run linux integration tests

**Comment by ArmandGrillet** [comment]
run linux integration tests

**Comment by ArmandGrillet** [comment]
run linux integration tests

**Comment by ArmandGrillet** [comment]
run all integration tests

**Pull request merged**
