### PR TITLE
Update Jenkinsfile for windows to properly rm -rf ${HOME}/.dcos 

### PR DESCRIPTION
**Pull request by klueska**

### CODE REVIEW

**Comment by klueska** [comment]
run windows integration tests

**Comment by klueska** [comment]
rerun windows integration tests

**Comment by klueska** [comment]
run windows integration tests

**Comment by klueska** [comment]
run windows integration tests

**Comment by klueska** [comment]
run windows integration tests

**Comment by klueska** [comment]
run windows integration tests

**Comment by klueska** [comment]
run windows integration tests

**Comment by bamarni** [comment]
just running windows integration tests so that it cleans the home folder, as for the CI failure in `test_setup_noninteractive` this should be fixed by #1048.

**Comment by bamarni** [comment]
run windows integration tests

**Comment by klueska** [comment]
Since #1048 and this PR mutually depend on each other to allow integration tests on windows to pass. I am going to go ahead and merge this patch in (since it's an obvious change) and then rerun the windows integration tests in #1048 to ensure they now pass.

**Comment by bamarni** [comment]
@klueska : is it possible that we have some concurrency issues with our builders? As we're using / deleting the default `~/.dcos` directory, this might affect other builds which could be running on the same node.

**Pull request merged**
