### PR TITLE
Edits to auth

### PR DESCRIPTION
**Pull request by joel-hamill**
Grammatical edits to the `dcos auth` command.

### CODE REVIEW

**Comment by joel-hamill** [comment]
CC: @emanic @tamarrow

**Comment by tamarrow** [comment]
thanks @joel-hamill can you make the same changes https://github.com/dcos/dcos-cli/blob/master/cli/tests/data/help/auth.txt as well?

**Comment by tamarrow** [comment]
closing in favor of #862

**Comment by joel-hamill** [comment]
@tamarrow done: https://github.com/dcos/dcos-cli/pull/864

**Pull request closed without merging**
