### PR TITLE
handle `dcos task` commands when no task is given

### PR DESCRIPTION
**Pull request by tamarrow**
#771

### CODE REVIEW

**Comment by cruhland** [comment]
@tamarrow code looks good. Waiting for tests to pass.

**Comment by tamarrow** [comment]
@cruhland thanks. In the future lets not `update branch` unless there are conflicts since it causes the tests to re-run.

**Comment by cruhland** [comment]
@tamarrow ok, I turned off the requirement for `master` to be up-to-date before we merge into it.

**Comment by cruhland** [comment]
@tamarrow hmm, that build has failed twice now with the same error.

**Pull request merged**
