### PR TITLE
config schema was not configured correctly.  resolving.

### PR DESCRIPTION
**Pull request by kensipe**

### CODE REVIEW

**Comment by tamarrow** [comment]
thanks @kensipe. Can we add a test for this please?

**Comment by tamarrow** [comment]
bump

**Comment by jimenez** [comment]
ping @kensipe ?

**Comment by kensipe** [comment]
@jimenez lost in priorities... on it today

**Comment by klueska** [comment]
Looks like you need a rebase.

**Comment by kensipe** [comment]
@klueska rebased

**Comment by kensipe** [comment]
rebased

**Comment by kensipe** [comment]
rebased

**Comment by kensipe** [comment]
rebased

**Comment by kensipe** [comment]
rebased

**Comment by bamarni** [comment]
run linux integration tests

**Comment by bamarni** [comment]
@kensipe : looking at the original issue, I am already able to reproduce the error with the current master : 
```
> dcos job --config-schema
{
  "$schema": "http://json-schema.org/schema#",
  "additionalProperties": false,
  "properties": {
    "service_name": {
      "description": "The name of the metronome cluster.",
      "title": "Name of the metronome cluster",
      "type": "string"
    },
    "url": {
      "description": "Api URL for talking to the Metronome scheduler.",
      "pattern": "^(?:(?:https?)://)(?:(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\\.?)+(?:[a-zA-Z]{2,6}\\.?|[a-zA-Z0-9-]{2,}\\.?)?|\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})(?::\\d+)?(?:/?|[/?]\\S+)$",
      "title": "Metronome service URL",
      "type": "string"
    }
  },
  "type": "object"
}
```

So this change is mainly about moving the config schema to the right place I suppose?

**Comment by kensipe** [comment]
@bamarni that is correct

**Pull request merged**
