### PR TITLE
Prepare the 0.7.8 release

### PR DESCRIPTION
**Pull request by bamarni**

### CODE REVIEW

**Comment by bamarni** [comment]
@mesosphere-ci run integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run integration tests

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run integration tests

**Pull request merged**
