### PR TITLE
Fixed broken integration tests.

### PR DESCRIPTION
**Pull request by klueska**
A number of marathon tests were failing on windows and blocking PRs from being merged. After looking at the tests and fixing them, it's not clear how they were ever working (even on linux/mac). I've updated them to be more stable both on linux/mac and on windows.

After fixing these issues, I noticed a bunch of other integration tests were failing as well. This PR is attempting to address all of these outstanding failing tests and turn them all green again.

### CODE REVIEW

**Comment by jsancio** [comment]
@klueska I updated #1001. There was a small bug in that PR. You may want to update this PR to include those changes.

**Comment by klueska** [comment]
Cool. Thanks Still working through some remaining failures (not just on windows anymore and mostly related to `test_package.py`).

**Comment by cruhland** [comment]
@klueska I'll review once the tests are in a good state. Let me know if those package tests are giving you trouble.

**Comment by klueska** [comment]
The one failing test on `continuous-integration/teamcity` is flaky, and the windows failure this time around is a node-provisioning failure. I will attempt to address both of these in subsequent PRs.

**Pull request merged**
