### PR TITLE
Bump `cryptography` lib to `2.0.2`

### PR DESCRIPTION
**Pull request by sschneid**

### CODE REVIEW

**Comment by sschneid** [comment]
@mesosphere-ci retest this please

**Comment by sschneid** [comment]
I'm not sure why this is failing CI on git checkout.  I'm unable trigger a rebuild, any ideas @klueska?

**Comment by klueska** [comment]
Not sure, I tried running the command it's hanging on locally and it succeeded.

**Comment by bamarni** [comment]
I'm having build errors when trying to setup CI on 0.4 which are also fixed by bumping this package (for now I've bumped it to `1.8.2` as I don't know if `2.0.2` introduces breaking changes). What I don't get is where is this package used? I can't find any reference to it in the codebase.

**Pull request merged**
