### PR TITLE
Bump `cryptography` lib to `1.8.2` (latest)

### PR DESCRIPTION
**Pull request by sschneid**

### CODE REVIEW

**Comment by sschneid** [comment]
@mesosphere-ci retest this please

**Comment by sschneid** [comment]
Hi @tamarrow -- could you please remind me what/how I need to manually test for this one?

**Comment by tamarrow** [comment]
authenticate with a service account on mac/linux/windows.

**Comment by ilovezfs** [comment]
This needs to be bumped to 1.8.2 (just released) to ensure compatibility with openssl 1.1.0f which does not works with < 1.8.2.

**Comment by sschneid** [comment]
Thanks for the heads up @ilovezfs; I'll update this PR.

**Comment by ilovezfs** [comment]
You're welcome. As another heads up, I have patched the Homebrew formula with this change already: https://github.com/Homebrew/homebrew-core/commit/5472944442ad2741bd6d0d7206194582cff45202

**Comment by sschneid** [comment]
@mesosphere-ci retest this please

**Comment by ilovezfs** [comment]
@sschneid note that 1.9 has since been released.

**Comment by sschneid** [comment]
Bah, thanks @ilovezfs -- I'll close this and make a new PR.

**Pull request closed without merging**
