### PR TITLE
Feature/framework id support

### PR DESCRIPTION
**Pull request by abridgett**
This adds the ability to find/list/log tasks filtered by framework ID.  Some frameworks (Spark for example) don't provide very unique task IDs and this is easier into the bargain.

It also fixes one issue with mesos.py where when "completed" was set, _only_ completed tasks were returned (the documentation claimed both were).

One buglet I can't see how to resolve is that the argument parsing forces the user to provide a task name for the "ls" and "logs" commands (I've tried a few approaches to no avail).

### CODE REVIEW

**Comment by jsancio** [comment]
@tamarrow can you take a look?

**Comment by abridgett** [comment]
Actually, there's a problem somewhere :-(  I'll do some more testing and find out what's going on.

**Comment by abridgett** [comment]
that's fixed one problem, still looking at the other (the directory that both ls and logs look at on the slave does not exist - the last ID is incorrect)

**Comment by abridgett** [comment]
Sorry about that - this seems to be better! I'll wait a bit and test more thoroughly next time.

**Comment by tamarrow** [comment]
@abridgett can you add some tests for this please?

**Comment by abridgett** [comment]
I'd love to but I must admit I'm finding it rather difficult to figure out how (mocked or unmocked), probably want to grab the frameworkID of marathon and look for those tasks (it seems that most test apps are run via marathon)

**Comment by tamarrow** [comment]
We should add tests here: https://github.com/mesosphere/dcos-cli/blob/master/cli/tests/integrations/test_task.py. These should give you some good test examples. Let me know if I can help. thanks!

**Comment by tamarrow** [comment]
@abridgett anything I can help with?

**Comment by tamarrow** [comment]
@abridgett I am closing this pr. If you would like to keep working on it, feel free to re-open.

**Pull request closed without merging**
