### PR TITLE
Make pagination a toggle

### PR DESCRIPTION
**Pull request by lloesche**
The current dcos-cli behaviour of paginating all output is uncommon for a Unix CLI tool and something you usually only see for commands that output entire man pages.

This PR allows the user to disable pagination.

Default is pagination=True to not break current behaviour.

### CODE REVIEW

**Comment by tamarrow** [comment]
@lloesche looks good, can you add tests for this please?

**Comment by lloesche** [comment]
@tamarrow I was wondering about that. How could I test if the pagination toggle works? When run in a CI server it's never going to have a tty, does it?
Do you have any good ideas?

**Comment by tamarrow** [comment]
How about using a mock? You can even just verify if `pydoc.pipepager` is called or not. see [here](https://github.com/dcos/dcos-cli/blob/master/cli/tests/unit/common.py)

**Comment by tamarrow** [comment]
^ @lloesche

**Comment by tamarrow** [comment]
taking over this pr #622

**Pull request closed without merging**
