### PR TITLE
add the .ps1 to activate for the powershell script

### PR DESCRIPTION
**Pull request by liqdfire**
Pr for Issue #687

### CODE REVIEW

**Comment by tamar22** [comment]
LGTM, thanks for the patch!

**Comment by tamar22** [comment]
ok to test

**Comment by tamarrow** [comment]
LGTM, thanks for the patch!

**Comment by tamarrow** [comment]
ok to test

**Comment by tamarrow** [comment]
@liqdfire can you please update your branch?

**Pull request merged**
