### PR TITLE
Change cf template name to cf template url

### PR DESCRIPTION
**Pull request by larioj**
This is the first step towards https://mesosphere.atlassian.net/browse/DCOS-11989

### CODE REVIEW

**Comment by larioj** [comment]
WIP

**Comment by larioj** [comment]
Closing and making change in experimental packaging

**Comment by tamarrow** [comment]
@larioj please don't add this to the other pr. We don't want a mega-pr, and we want the other pr merged asap.

**Comment by larioj** [comment]
@tamarrow I'd like to enable the tests on this PR to show that the CI changes are working correctly?

**Pull request merged**
