### PR TITLE
When describing a package print the full response

### PR DESCRIPTION
**Pull request by jsancio**

### CODE REVIEW

**Comment by klueska** [comment]
This looks like a legitimate failure. Did you try running the test suite locally before pushing?

https://teamcity.mesosphere.io/viewLog.html?buildId=689667&buildTypeId=DcosIo_DcosCli_OsX_MacBinary&guest=1

**Comment by klueska** [comment]
Maybe you need a rebase on master?

**Comment by jsancio** [comment]
Yes. It is a work in progress. I'll ping when it is ready.

**Comment by jsancio** [comment]
@klueska Can we merge this? Did we commit your change to master?

**Comment by klueska** [comment]
I didn't commit my change to master yet, but I know what the problem is and I see your changes that aren't platform specific. Given that we pass on both Linux and Windows, I'm happy to merge this as-is.

**Comment by jsancio** [comment]
Thanks @klueska !

**Pull request merged**
