### PR TITLE
Post CI failures on slack

### PR DESCRIPTION
**Pull request by bamarni**
Whenever a Jenkins build for the main branches fails, a notification will be posted to the #dcos-cli-ci Slack channel

### CODE REVIEW

**Comment by bamarni** [comment]
run linux integration tests

**Comment by bamarni** [comment]
run linux integration tests

**Comment by bamarni** [comment]
run linux integration tests

**Comment by bamarni** [comment]
run linux integration tests

**Comment by bamarni** [comment]
run linux integration tests

**Comment by bamarni** [comment]
run linux integration tests

**Comment by bamarni** [comment]
run linux integration tests

**Comment by bamarni** [comment]
run linux integration tests

**Comment by bamarni** [comment]
run linux integration tests

**Comment by bamarni** [comment]
run linux integration tests

**Comment by bamarni** [comment]
run linux integration tests

**Comment by bamarni** [comment]
run linux integration tests

**Comment by vespian** [comment]
@bamarni BTW, could you please prepare a PR that will add [1] https://github.com/mesosphere/sec-ci-libs#pull-request-authorizer-for-community-contributions to the repo? Long story short it is a requirement, even for our private repos.

[1] https://github.com/mesosphere/sec-ci-libs#pull-request-authorizer-for-community-contributions

**Comment by bamarni** [comment]
@vespian : is it a requirement to use this specific solution, or to block builds from external contributors  and have a way to manually trigger them?

**Comment by vespian** [comment]
>  is it a requirement to use this specific solution, or to block builds from external contributors and have a way to manually trigger them?

Yes, this is a requirement, yes we need to use `user_is_authorized` specifically, yes, even if the repo is private/does not accept community contributions :)

**Pull request merged**
