### PR TITLE
Add full stops to all error string representations which did not have…

### PR DESCRIPTION
**Pull request by adamtheturtle**
… them.

See https://jira.mesosphere.com/browse/DCOS_OSS-1604

### CODE REVIEW

**Comment by adamtheturtle** [comment]
cc @bamarni @klueska

**Comment by bamarni** [comment]
run all integration tests

**Comment by bamarni** [comment]
@adamtheturtle : did you run the test suite of the dcos package locally? It's syntax and unit tests, unfortunately we cannot have them on the CI yet, not until some minor fixes are addressed (#1038 and #1054).

**Comment by adamtheturtle** [comment]
@bamarni `make test` now passes locally.

**Comment by bamarni** [comment]
run all integration tests

**Comment by adamtheturtle** [comment]
@bamarni Done and thanks for your patience!

**Comment by adamtheturtle** [comment]
run all integration tests

**Comment by adamtheturtle** [comment]
I have merge `origin/master` in but I am confused. CI showed the following error:

```
Using context: linux-binary
ERROR: Branch not suitable for integration as it does not merge cleanly: Command "git merge --ff a6f3c9a29213ee343fc70e5d0312e171c64f0f5c" returned status code 128:
stdout: 
stderr: 
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@mesos-jenkins-dd12c2b2d45244a3976a9d45087c6d96-py35.(none)')

Finished: FAILURE
```

but GitHub showed "This branch has no conflicts with the base branch".

cc @bamarni - any ideas?

**Comment by adamtheturtle** [comment]
run all integration tests

**Comment by bamarni** [comment]
@adamtheturtle : I had just closed this as I thought this occured when there were conflicts with master? https://jira.mesosphere.com/browse/DCOS_OSS-1634

Did you have any conflicts to resolve? Or was it just not up-to-date?

**Comment by adamtheturtle** [comment]
> Did you have any conflicts to resolve? Or was it just not up-to-date?

@bamarni I had no conflicts to resolve. I was just not up-to-date.

**Comment by bamarni** [comment]
I'm reopening the jira then as I had misunderstood, it shouldn't fail if there is no conflict.

**Comment by adamtheturtle** [comment]
run all integration tests

**Comment by adamtheturtle** [comment]
run all integration tests

**Pull request merged**
