### PR TITLE
allow metronome schedule updates to not require an array

### PR DESCRIPTION
**Pull request by kensipe**
fixes bug found on schedule update which force schedules to be in an array.  
now there can be 1 or 1 in an array.

### CODE REVIEW

**Comment by kensipe** [comment]
fixes: https://jira.mesosphere.com/browse/DCOS_OSS-1584

**Comment by kensipe** [comment]
huh?  `[linux-tests] tests/integrations/test_cluster.py::test_setup_noninteractive FAILED`

**Comment by bamarni** [comment]
@kensipe : I'm taking a look at it

**Comment by bamarni** [comment]
See #1048 , this change would allow us to get the exact stdout / stderr in case this reproduces. Then we can take necessary actions (increase timeout, change the way to test it, etc.), but today is the first time is see it failing, this might be due to slow networking conditions or similar.

**Comment by kensipe** [comment]
@mesosphere-ci "retest this please"

**Comment by kensipe** [comment]
@mesosphere-ci retest this please

**Comment by kensipe** [comment]
@klueska @bamarni is there anything preventing a merge?

**Comment by kensipe** [comment]
rebased

**Comment by bamarni** [comment]
run linux integration tests

**Comment by kensipe** [comment]
@bamarni looking green :)

**Comment by bamarni** [comment]
Thanks @kensipe

**Pull request merged**
