### PR TITLE
Check for plugin viability when adding it to the CLI.

### PR DESCRIPTION
**Pull request by ArmandGrillet**

### CODE REVIEW

**Comment by ArmandGrillet** [comment]
@mesosphere-backup run integration tests

**Comment by ArmandGrillet** [comment]
@mesosphere-backup run integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run all integration tests

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run integration tests

**Comment by rgo3** [comment]
@mesosphere-ci run integration tests

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run integration tests

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run integration tests

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run integration tests

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run integration tests

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run integration tests

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run integration tests

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run integration tests

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run integration tests

**Comment by ArmandGrillet** [comment]
On Windows:
```
================================== FAILURES ===================================
_____________________________ test_plugin_remove ______________________________

default_cluster = {'acs_token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1aWQiOiJ0ZXN0dXNlciIsImV4cCI6MTU1MzAxMTk4OX0.Ga06WTeHgKLd4Fw_Js...4bc-75f982fee0bb', 'dcos_url': 'http://52.10.33.205', 'name': 'test_cluster_c12da9f7-4e5a-4a8e-bc17-0889d0ed99eb', ...}

    def test_plugin_remove(default_cluster):
        _install_test_plugin()
    
        code, out, err = exec_cmd(['dcos', 'plugin', 'remove', 'dcos-test'])
>       assert code == 0
E       assert 1 == 0

integration\test_plugin.py:221: AssertionError
```

**Comment by ArmandGrillet** [comment]
@mesosphere-ci run integration tests

**Pull request merged**
