### PR TITLE
Bump the 0.5.x branch for the 1.10.1 release.

### PR DESCRIPTION
**Pull request by klueska**

### CODE REVIEW

**Comment by klueska** [comment]
run all integration tests

**Comment by bamarni** [comment]
run all integration tests

**Comment by bamarni** [comment]
this is fixed in master but not backported to 0.5 branch yet

**Comment by klueska** [comment]
rerun all integration tests

**Comment by bamarni** [comment]
@klueska : This commit (https://github.com/dcos/dcos-cli/pull/1088/commits/158ffb7fd288b568a2cb63d061b1c00a3bc41dc7) is some clean-up after the removal of experimental features (https://github.com/dcos/dcos-cli/pull/1079), as this targets DC/OS 1.11 we didn't plan it for backport to 0.5. So removing that commit should fix the CI issue.

**Comment by klueska** [comment]
run linux integration tests

**Comment by klueska** [comment]
run mac integration tests
run windows integration tests

**Comment by klueska** [comment]
run mac integration tests

**Comment by klueska** [comment]
run windows integration tests

**Pull request merged**
