### PR TITLE
The linkerd package has a syntax error; switch to hello-world

### PR DESCRIPTION
**Pull request by cruhland**
This is a quick fix to get the tests passing. I will file a separate JIRA to fix the problem with `linkerd`.

### CODE REVIEW

**Comment by cruhland** [comment]
@jimenez @tamarrow the Windows build seems broken, it keeps failing on tests unrelated to my change. Any ideas?

**Comment by benclarkwood** [comment]
I too have been encountering this elsewhere. :(

**Comment by klueska** [comment]
Good news: I was able to get a local windows dev environment set up and am able to reproduce the errors we're seeing on windows.

Bad news: It took me 1.5 days to set up and get working, so it will have to wait till Monday to get debugged.

**Comment by klueska** [comment]
I have a PR out to fix the windows build now: https://github.com/dcos/dcos-cli/pull/1004

**Pull request merged**
