### PR TITLE
rename snapshot command

### PR DESCRIPTION
**Pull request by darkonie**
a new command to manage a set of cluster logs would be:
dcos node diagnostics ...

a zip file with collected logs is now called a `diagnostics bundle`

### CODE REVIEW

**Comment by tamarrow** [comment]
@darkonie we're going to have to add deprecation notices on the `snapshot` commands

**Comment by darkonie** [comment]
@tamarrow thanks, will do

**Comment by malnick** [comment]
@tamarrow Is that neccessary? Have we actually released the snapshot command to the community yet? 1.8EA isn't until Monday. 

CC @spahl

**Comment by jsancio** [comment]
I think we fix it before EA then we don't need to add a deprecation warning.

**Comment by tamarrow** [comment]
okay

**Pull request merged**
