### PR TITLE
Update the master branch for 1.13

### PR DESCRIPTION
**Pull request by bamarni**
- Use DC/OS 1.13 in integration tests
- Bundle the 1.13 testing plugin in the master builds

### CODE REVIEW

**Comment by bamarni** [comment]
@mesosphere-ci run integration tests

**Comment by bamarni** [comment]
@mesosphere-ci run integration tests

**Comment by pcrews** [comment]
@mesosphere-ci : run integration tests

**Comment by bamarni** [comment]
@mesosphere-ci : run integration tests

**Pull request merged**
