### PR TITLE
Prepare 1.1.0 release

### PR DESCRIPTION
**Pull request by bamarni**
This updates the completion script and changelog for the next 1.1.0 release.

### CODE REVIEW

**Comment by makkes** [comment]
Integration tests are failing b/c the URL is different.

**Comment by makkes** [comment]
@bamarni, somehow the jenkins job is not triggering...

**Comment by bamarni** [comment]
@makkes Unless we changed the config already, it is built with the trigger phrase

**Comment by bamarni** [comment]
@mesosphere-ci run integration tests

**Pull request merged**
